name: Publish Package to npmjs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: can-npm-publish
        run: npx can-npm-publish --verbose
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: enable pnpm
        run: corepack enable
      - name: install dependencies
        run: pnpm install --frozen-lockfile --prod
      - name: build
        run: pnpm build
      - name: release
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
