name: Publish Package to npmjs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: can-npm-publish
        run: npx can-npm-publish --verbose
      - uses: volta-cli/action@v3
        with:
          registry-url: https://registry.npmjs.org
          always-auth: true
      - run: corepack enable
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: build
        run: pnpm build
      - name: release
        run: pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}