name: Publish Package to npmjs
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: can-npm-publish
        run: npx can-npm-publish --verbose
      - uses: volta-cli/action@v3
        with:
          registry-url: https://registry.npmjs.org
          always-auth: true
      - name: install dependencies
        run: yarn install --frozen-lockfile --prod
      - name: build
        run: yarn build
      - name: release
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
